server:
  port: 8080

spring:
  jmx:
    enabled: false
  security:
    saml2:
      relyingparty:
        registration:
          keycloak:
            entity-id: spring-sp-demo
            assertingparty:
              metadata-uri: classpath:credentials/idp-metadata.xml
            signing:
              credentials:
                - private-key-location: classpath:credentials/sp.key
                  certificate-location: classpath:credentials/sp.crt
            decryption:
              credentials:
                - private-key-location: classpath:credentials/sp.key
                  certificate-location: classpath:credentials/sp.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"

logging:
  level:
    org.springframework.security: DEBUG
